language: python

script:
  - tox

addons:
  apt:
    packages:
      - slapd
      - ldap-utils

install:
  - pip install tox

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-django18
    - python: "2.7"
      env: TOXENV=py27-django110
    - python: "2.7"
      env: TOXENV=py27-django110
    - python: "3.4"
      env: TOXENV=py34-django18
    - python: "3.4"
      env: TOXENV=py34-django110
    - python: "3.4"
      env: TOXENV=py34-django111

    # Python 3.4/3.5 are close enough, don't test all combinations.
    - python: "3.5"
      env: TOXENV=py35-django111

    # Linting
    - python: "3.4"
      env: TOXENV=lint

notifications:
  email: false
  irc: "irc.freenode.org#xelnext"
