language: python
python:
  - "2.7"
env:
  - DJANGO=Django==1.2.7
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.15
  - DJANGO=Django==1.5.10
  - DJANGO=Django==1.6.7
  - DJANGO=Django==1.7
install:
  - pip install -q $DJANGO python-ldap mockldap --use-mirrors
script: python manage.py test ldapdb examples
